/*
 * Screenshot Capture API
 * Webseite-Herunterladen.de Screenshot Capture is a very simple but powerful screenshot API that anyone can easily use to create pixel-perfect website screenshots. It always uses a recent version of Chrome to ensure that all modern web features are fully supported and rendering is exactly as your customers would expect.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import io.swagger.client.model.ErrorModel;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScreenshotApi
 */
@Ignore
public class ScreenshotApiTest {

    private final ScreenshotApi api = new ScreenshotApi();

    /**
     * 
     *
     * Webseite-Herunterladen.de Screenshot Capture is a very simple but powerful screenshot API that anyone can easily use to create pixel-perfect website screenshots. It always uses a recent version of Chrome to ensure that all modern web features are fully supported and rendering is exactly as your customers would expect.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void captureScreenshotAuthenticatedTest() throws ApiException {
        String token = null;
        String hash = null;
        String url = null;
        String fileType = null;
        Long ttl = null;
        Boolean invalidate = null;
        Boolean full = null;
        Boolean lazyloadScroll = null;
        Long delay = null;
        Long width = null;
        Long height = null;
        Long quality = null;
        BigDecimal scale = null;
        Long x = null;
        Long y = null;
        Boolean redirect = null;
        String language = null;
        Boolean randomUserAgent = null;
        String userAgent = null;
        String headers = null;
        String cookies = null;
        String css = null;
        String js = null;
        String wait = null;
        String element = null;
        String timezone = null;
        String device = null;
        BigDecimal latitude = null;
        BigDecimal longitude = null;
        BigDecimal accuracy = null;
        String proxy = null;
        Boolean adblock = null;
        Boolean hideCookieBanners = null;
        File response = api.captureScreenshotAuthenticated(token, hash, url, fileType, ttl, invalidate, full, lazyloadScroll, delay, width, height, quality, scale, x, y, redirect, language, randomUserAgent, userAgent, headers, cookies, css, js, wait, element, timezone, device, latitude, longitude, accuracy, proxy, adblock, hideCookieBanners);

        // TODO: test validations
    }
    /**
     * 
     *
     * Webseite-Herunterladen.de Screenshot Capture is a very simple but powerful screenshot API that anyone can easily use to create pixel-perfect website screenshots. It always uses a recent version of Chrome to ensure that all modern web features are fully supported and rendering is exactly as your customers would expect.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void captureScreenshotUnauthenticatedTest() throws ApiException {
        String token = null;
        String url = null;
        String fileType = null;
        Long ttl = null;
        Boolean invalidate = null;
        Boolean full = null;
        Boolean lazyloadScroll = null;
        Long delay = null;
        Long width = null;
        Long height = null;
        Long quality = null;
        BigDecimal scale = null;
        Long x = null;
        Long y = null;
        Boolean redirect = null;
        String language = null;
        Boolean randomUserAgent = null;
        String userAgent = null;
        String headers = null;
        String cookies = null;
        String css = null;
        String js = null;
        String wait = null;
        String element = null;
        String timezone = null;
        String device = null;
        BigDecimal latitude = null;
        BigDecimal longitude = null;
        BigDecimal accuracy = null;
        String proxy = null;
        Boolean adblock = null;
        Boolean hideCookieBanners = null;
        File response = api.captureScreenshotUnauthenticated(token, url, fileType, ttl, invalidate, full, lazyloadScroll, delay, width, height, quality, scale, x, y, redirect, language, randomUserAgent, userAgent, headers, cookies, css, js, wait, element, timezone, device, latitude, longitude, accuracy, proxy, adblock, hideCookieBanners);

        // TODO: test validations
    }
}
